services:
  app2:
    image: xtaoi/todo-app:v1.0.2-maria-nginx   # Image มี Nginx + Next.js ในตัวแล้ว
    container_name: app2
    ports:
      - "8081:80"              # Nginx port (ไม่ใช่ 3000 แล้ว)
      # - "443:443"          # Uncomment for SSL
    environment:
      # เลือก DB runtime
      DB_TYPE: postgres    # เปลี่ยนเป็น postgres / mariadb / mongo ได้ตามต้องการ

      # MariaDB
      MARIADB_HOST: mariadb
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_PORT: 3306

      # Postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: todo_app
      POSTGRES_PORT: 5432

      # MongoDB
      MONGO_HOST: mongo
      MONGO_USER: todo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: todo_app
      MONGO_PORT: 27017

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net
    # depends_on:
    #   - mariadb
    #   - postgres
    #   - mongo

networks:
  todo-net:
    external: true   # ต้องมี network ของ DB สร้างไว้ก่อน